In [1]:
## extract & check bounding box (defect data) from matlab files
# https://towardsdatascience.com/how-to-load-matlab-mat-files-in-python-1f200e1287b5
# https://machinelearningmastery.com/how-to-develop-a-convolutional-neural-network-to-classify-photos-of-dogs-and-cats/#comment-516177

# imports
import sys
import os
import pandas as pd
import numpy as np

In [ ]:
# paper
# https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0203192#sec015
# database of 2042 real images: 530 images of defective metallic boxes and 1512 images of non-defective ones.
# train : 75% of the images, i.e. 1531 images, 1148 with defects and 397 without defects

# divided all the images into patches of size 32 × 32. 
# Patches that contain defects are then treated as negative examples while the remaining are treated as positive examples.

In [2]:
# check version installed
print(sys.version)   # prints python version
print('')
print(pd.__version__)
print("")
print(np.__version__)

3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]

0.25.0

1.17.0


In [3]:
import scipy
print(scipy.__version__)

1.3.0


In [5]:
# load matlab file
from scipy.io import loadmat
annots = loadmat('DB_wHaar.mat')

In [6]:
annots

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri Oct 06 16:04:40 2017',
 '__version__': '1.0',
 '__globals__': [],
 'imagesTrain': array([[ 1,  4,  3, ...,  5, 10,  2],
        [ 6,  6,  3, ...,  3,  8,  2],
        [10,  6,  0, ...,  3,  4,  1],
        ...,
        [15, 23, 14, ...,  7,  1, 15],
        [14, 14, 27, ...,  3,  9, 11],
        [ 1, 12, 15, ...,  4, 18,  6]], dtype=uint16),
 'labelsTrain': array([[0, 0, 0, ..., 1, 1, 1]], dtype=uint8)}

In [7]:
from sys import getsizeof
getsizeof(annots)

240

In [9]:
annots.keys()

dict_keys(['__header__', '__version__', '__globals__', 'imagesTrain', 'labelsTrain'])

In [10]:
annots['imagesTrain']

array([[ 1,  4,  3, ...,  5, 10,  2],
       [ 6,  6,  3, ...,  3,  8,  2],
       [10,  6,  0, ...,  3,  4,  1],
       ...,
       [15, 23, 14, ...,  7,  1, 15],
       [14, 14, 27, ...,  3,  9, 11],
       [ 1, 12, 15, ...,  4, 18,  6]], dtype=uint16)

In [11]:
annots['imagesTrain'][0]

array([ 1,  4,  3, ...,  5, 10,  2], dtype=uint16)

In [15]:
annots['imagesTrain'][0][0]

1

In [17]:
# size of array
annots['imagesTrain'].size

47384610

In [18]:
annots['imagesTrain'][0].size

2042

In [19]:
len(annots['imagesTrain'][0])

2042

In [20]:
annots['imagesTrain'].shape

(23205, 2042)

In [21]:
annots['labelsTrain'].size

2042

In [12]:
annots['labelsTrain']

array([[0, 0, 0, ..., 1, 1, 1]], dtype=uint8)

In [13]:
len(annots['labelsTrain'])

1

In [14]:
len(annots['imagesTrain'])

23205